debugging

diff --git a/installdwm b/installdwm
--- a/installdwm
+++ b/installdwm
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 read -p "This script installs and configures a minimally riced and highly configurable dwm system with dmenu and suckless terminal
-answer\ndo you wish to continue? [y/n]" answer
+do you wish to continue? [y/n]" answer
 
 # function to check if a program is installed
 is_installed() {
@@ -11,8 +11,9 @@ is_installed() {
 if [ "$answer" = "y" ] || [ "$answer" = "Y" ] || [ "$answer" = "yes" ] || [ "$answer" = "Yes" ]; then
     echo setting up dwm, dmenu and st...
 
-    if is_installed dmenu && is_installed dwm && is_installed st; then
-        echo "demnu, dwm, and st are already installed"
+    if is_installed dmenu || is_installed dwm || is_installed st; then
+        echo "build error"
+        exit 1
 
     else
 	# download and install dmenu, dwm, and st
@@ -25,10 +26,13 @@ if [ "$answer" = "y" ] || [ "$answer" = "Y" ] || [ "$answer" = "yes" ] || [ "$an
         sudo pacman -S --needed libxinerama
         cd ~/.local/src/dmenu || exit 
         make clean install
+        sleep 5
         cd ~/.local/src/dwm || exit
         make clean install 
+        sleep 5
 	cd ~/.local/src/st || exit
         make clean install
+        sleep 5
         cd ~ || exit
         cp /etc/X11/xinit/xinitrc ~/.xinitrc
     
@@ -38,6 +42,11 @@ if [ "$answer" = "y" ] || [ "$answer" = "Y" ] || [ "$answer" = "yes" ] || [ "$an
         total_lines=$(wc -l < "$file")
         start_line=$((total_lines - 5))
         sed -i "${start_line},\$d; \$aexec dwm" "$file"
+        cat ~/.xinitrc
+        read -p "is execdwm at bottom" answer
+        if [ "$answer" = "n" ] || [ "$answer" = "N" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ]; then
+            exit 1 
+        fi
     fi  
 
 elif [ "$answer" = "n" ] || [ "$answer" = "N" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ]; then
