debigging

diff --git a/installdwm b/installdwm
--- a/installdwm
+++ b/installdwm
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 read -p "This script installs and configures a minimally riced and highly configurable dwm system with dmenu and st (simple terminal)
 do you wish to continue? [y/n]" answer
@@ -19,30 +19,23 @@ if [ "$answer" = "y" ] || [ "$answer" = "Y" ] || [ "$answer" = "yes" ] || [ "$an
 	# download and install dmenu, dwm, and st
         mkdir -p ~/.local/src
         cd ~/.local/src || exit
-        git clone https://github.com/bugswriter/dmenu
-        git clone https://github.com/bugswriter/dwm
-        git clone https://github.com/bugswriter/st
+        git clone https://github.com/bugswriter/dmenu || echo 'Failed to clone dmenu'; exit 1;;
+        git clone https://github.com/bugswriter/dwm || echo 'Failed to clone dwm'; exit 1;;
+        git clone https://github.com/bugswriter/st || echo 'Failed to clone st'; exit 1;;
         sudo pacman -S --needed libxft
         sudo pacman -S --needed libxinerama
         cd ~/.local/src/dmenu || exit 
-        make clean install
-        sleep 5
+        make clean install || echo 'Failed to make dmenu'; exit 1;;
         cd ~/.local/src/dwm || exit
-        make clean install 
-        sleep 5
+        make clean install || echo 'Failed to make dwm'; exit 1;;
         cd ~/.local/src/st || exit
-        make clean install
-        sleep 5
+        make clean install || echo 'Failed to make st'; exit 1;;
         cd ~ || exit
         cp /etc/X11/xinit/xinitrc ~/.xinitrc
     
 # Update .xinitrc to exec dwm on startx
         head -n -5 $HOME/.xinitrc > temp.txt && mv temp.txt $HOME/.xinitrc
         echo 'exec dwm' >> $HOME/.xinitrc 
-        read -p "is execdwm at bottom" answer
-        if [ "$answer" = "n" ] || [ "$answer" = "N" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ]; then
-            exit 1 
-        fi
     fi  
 
 elif [ "$answer" = "n" ] || [ "$answer" = "N" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ]; then
