debugging

diff --git a/rice b/rice
--- a/rice
+++ b/rice
@@ -7,28 +7,29 @@ echo establishing resolution...
     do  
     echo finding current resolution settings...
     xrandr 
-       echo please enter the name of your monitor or screen i.e. Virtual1'\n'
-       read monitor_name
-       echo please enter your desired resolution i.e. 1920x1080
-       read resolution
-       xrandr --output $monitor_name --mode $resolution
+        echo -p 'please enter the name of your monitor or screen i.e. Virtual-1' monitor_name
+        echo -p 'please enter your desired resolution i.e. 1920x1080' resolution
+        xrandr --output $monitor_name --mode $resolution
         read -p "would you like to make changes to the resolution? [y/n]" answer 
-        if [ "$answer" = "n" -o "$answer" = "no" -o "$answer" = "No" -o "$answer" = "NO" ]; then
+        if [ "$answer" = "n" ] || [ "$answer" = "no" ] || [ "$answer" = "No" ] || [ "$answer" = "NO" ]; then
             break
+        elif [ "$answer" = "y" ] || [ "$answer" = "yes" ] || [ "$answer" = "Yes" ] || [ "$answer" = "YES" ]; then
+            continue
+        else
+            echo 'invalid input aborting script' && exit 1
         fi
     done
     
     sudo pacman -S --needed wget
-    echo setting up wallpaper management...
+    echo 'Setting up wallpaper management...'
     cd ~
     sudo pacman -S --needed xwallpaper
     mkdir wallpapers
     
     # use default wallpaper
     wget 'https://w.wallhaven.cc/full/3l/wallhaven-3lrw69.jpg' -O '~/wallpapers/windwaker.jpg'
-    
-    
-    echo installing zsh and zimfw framework...
+     
+    echo 'installing zsh and zimfw framework...'
     sudo pacman -S --needed zsh
     chsh -s $(which zsh)
     curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
@@ -36,30 +37,21 @@ echo establishing resolution...
     setsid xcompmgr
     
     sudo pacman -S python-pywal
-    if [ -d "$HOME/.local/bin" ]; then 
-	echo bin already exists delete it to proceed? [y/n] 
-	read answer
-        if [ "$answer" = "n" -o "$answer" = "N" -o "$answer" = "no" -o "$answer" = "No" ]; then
-            echo aborting rice
-            exit 0
-        fi
-    fi
     cd $HOME/.local
-    git clone https://github.com/Steven-Alvarado/bin.git
+    git clone https://github.com/Steven-Alvarado/bin.git 
     chmod +x $HOME/.local/bin/*
     cd $HOME/.local/bin
     rm -rf dwmblocks
     git clone https://github.com/bugswriter/dwmblocks.git
     cd dwmblocks
     sudo make install
-    sleep 5
     cd $HOME/.local/bin
     
     sudo pacman -S xdotool
     ./imagine $HOME/wallpapers/windwaker.jpg
     
     # Export path to ~/.local/bin in zsh
-    echo -e "\nexport PATH=$HOME/.local/bin:$PATH" >> ~/.zshrc
+    echo -e '\nexport PATH=$HOME/.local/bin:$PATH' >> ~/.zshrc
     
     
     # Set up .xinitrc file to run tools on start-up
